services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - "80:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/usb_vault:/mnt/usb_vault:ro
      - ./homepage/config:/app/config
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=tingserver,100.123.39.79
    env_file:
      - ./homepage/config/secrets.env
    restart: unless-stopped

  glances:
    image: nicolargo/glances:latest
    container_name: glances
    restart: unless-stopped
    pid: host
    network_mode: host
    environment:
      - GLANCES_OPT=-w

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud_vault
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - /mnt/usb_vault/nextcloud_data:/var/www/html

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:80"
    environment:
      - TZ=Asia/Kuala_Lumpur
      - FTLCONF_dns_listeningMode=All
    env_file:
      - ./homepage/config/secrets.env
    dns:
      - 127.0.0.1
      - 1.1.1.1
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped

  speedtest:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest
    ports:
      - "8082:80"
    environment:
      - TZ=Asia/Kuala_Lumpur
      - APP_TIMEZONE=Asia/Kuala_Lumpur
      - PUID=1000
      - PGID=1000
      - APP_URL=http://100.123.39.79:8082
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE=0 * * * *
    env_file:
      - ./homepage/config/secrets.env
    volumes:
      - ./speedtest/config:/config
    restart: unless-stopped

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - "8083:80"
    environment:
      - TZ=Asia/Kuala_Lumpur
      - WEBSOCKET_ENABLED=true
    env_file:
      - ./homepage/config/secrets.env
    volumes:
      - /mnt/usb_vault/vaultwarden_data:/data
